const actions = {
  BUY_CAKE: "BUY_CAKE",
  BUY_ICE_CREAM: "BUY_ICE_CREAM",
  GET_USERS: "GET_USERS",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE"
};

export default actions;
