const postActions = {
  GET_POST_BY_ID: "GET_POST_BY_ID",
  GET_POSTS: "GET_POSTS",
  GET_POST_BY_ID_SUCCESS: "GET_POST_BY_ID_SUCCESS",
  FETCH_POST_BY_ID_SUCCESS: "FETCH_POST_BY_ID_SUCCESS",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POST_BY_ID_FAILURE: "GET_POST_BY_ID_FAILURE"
};

export default postActions;
